# Generated by Django 4.0.3 on 2022-03-29 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_question', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255)),
                ('publish_question', models.DateField(default=datetime.date.today)),
                ('answer', models.TextField()),
                ('publish_answer', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='user_admin', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
