# Generated by Django 4.0.3 on 2022-03-30 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
