# Generated by Django 4.0.3 on 2022-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='publish',
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
