# Generated by Django 4.0.3 on 2022-03-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question'),
        ),
    ]
